from scripts.constants import OUTPUT_DIR


def write_files(blacklist, whitelist):

        OUTPUT_DIR.mkdir(exist_ok=True, parents=True)

        block_file = OUTPUT_DIR / "blocklist.txt"
        white_file = OUTPUT_DIR / "whitelist.txt"
        smartdns_file = OUTPUT_DIR / "smartdns.conf"

        blacklist = sorted(set(blacklist))
        whitelist = sorted(set(whitelist))

        with open(block_file, "w", encoding="utf-8") as f:
                f.write("\n".join(blacklist))

            with open(white_file, "w", encoding="utf-8") as f:
                f.write("\n".join(whitelist))

            with open(smartdns_file, "w", encoding="utf-8") as f:
                f.write("# SmartDNS DNS rules\n")
                f.write("# Generated by LoogCP/adrules\n")
                f.write("#\n")
                f.write("# Blacklist: return SOA\n")
                f.write("# Whitelist: ignore address rule\n")
                f.write("\n")

                f.write("# ===== Blacklist =====\n")
                for domain in blacklist:
                        f.write(f"address /{domain}/#\n")

                    f.write("\n")
                f.write("# ===== Whitelist =====\n")
                for domain in whitelist:
                        f.write(f"address /{domain}/-\n")
